routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware('hasAllowedIPAddress')->group(function () {


    Auth::routes();


    Route::prefix('/dashboard')->middleware('isAdminUser')->group(function () {
        Route::get('/', 'Admin\DashboardController@index')->name('dashboard');

        // Users
        Route::prefix('users')->name('users.')->group(function () {
            Route::get('/', 'Admin\UsersController@index')->name('index');
            Route::get('/create', 'Admin\UsersController@create')->name('create');
            Route::post('/store', 'Admin\UsersController@store')->name('store');
            Route::get('/edit/{id}', 'Admin\UsersController@edit')->name('edit');
            Route::post('/update/{id}', 'Admin\UsersController@update')->name('update');
            Route::get('/delete/{id}', 'Admin\UsersController@delete')->name('delete');
        });

        // Products
        Route::prefix('products')->name('products.')->group(function () {

            Route::get('/', 'Admin\ProductsController@index')->name('index');
            Route::get('/create', 'Admin\ProductsController@create')->name('create');
            Route::post('/store', 'Admin\ProductsController@store')->name('store');
            Route::get('/edit/{id}', 'Admin\ProductsController@edit')->name('edit');
            Route::post('/update/{id}', 'Admin\ProductsController@update')->name('update');
            Route::get('/delete/{id}', 'Admin\ProductsController@delete')->name('delete');
            Route::get('/get-products-index-table/{id}/{search}', 'Admin\ProductsController@getProductsIndexTable')->name('get_products_index_table');
        });

        // Categories
        Route::prefix('categories')->name('categories.')->group(function () {

            Route::get('/', 'Admin\CategoriesController@index')->name('index');
            Route::get('/create', 'Admin\CategoriesController@create')->name('create');
            Route::post('/store', 'Admin\CategoriesController@store')->name('store');
            Route::get('/edit/{id}', 'Admin\CategoriesController@edit')->name('edit');
            Route::post('/update/{id}', 'Admin\CategoriesController@update')->name('update');
            Route::get('/delete/{id}', 'Admin\CategoriesController@delete')->name('delete');
            Route::get('/get-categories-index-table/{search}', 'Admin\CategoriesController@getCategoriesIndexTable')->name('get_categories_index_table');
        });

        // Vats
        Route::prefix('vats')->name('vats.')->group(function () {

            Route::get('/', 'Admin\VatsController@index')->name('index');
            Route::get('/create', 'Admin\VatsController@create')->name('create');
            Route::post('/store', 'Admin\VatsController@store')->name('store');
            Route::get('/edit/{vat}', 'Admin\VatsController@edit')->name('edit');
            Route::post('/update/{vat}', 'Admin\VatsController@update')->name('update');
            Route::get('/delete/{vat}', 'Admin\VatsController@delete')->name('delete');
            Route::get('/get-vats-index-table/{search}', 'Admin\VatsController@getVatsIndexTable')->name('get_vats_index_table');
        });

        Route::prefix('orders')->name('orders.')->group(function () {
            Route::get('/', 'Admin\OrdersController@index')->name('index');
        });

        // Allergies
        Route::prefix('allergies')->name('allergies.')->group(function () {

            Route::get('/', 'Admin\AllergiesController@index')->name('index');
            Route::get('/create', 'Admin\AllergiesController@create')->name('create');
            Route::post('/store', 'Admin\AllergiesController@store')->name('store');
            Route::get('/edit/{allergy}', 'Admin\AllergiesController@edit')->name('edit');
            Route::post('/update/{allergy}', 'Admin\AllergiesController@update')->name('update');
            Route::get('/delete/{allergy}', 'Admin\AllergiesController@delete')->name('delete');
            Route::get('/get-index-table/{search}', 'Admin\AllergiesController@getIndexTable')->name('get_index_table');
        });

        // Discounts
        Route::prefix('discounts')->name('discounts.')->group(function () {

            Route::get('/', 'Admin\DiscountsController@index')->name('index');
            Route::get('/create', 'Admin\DiscountsController@create')->name('create');
            Route::post('/store/{product}', 'Admin\DiscountsController@store')->name('store');
            Route::get('/edit/{product}', 'Admin\DiscountsController@edit')->name('edit');
            Route::post('/update/{product}', 'Admin\DiscountsController@update')->name('update');
        });
    });

    // Orders
    Route::prefix('orders')->name('orders.')->group(function () {

        Route::get('/success/{order}', 'OrdersController@success')->name('success');
        Route::post('/store', 'OrdersController@store')->name('store');
        Route::post('/update/{order}', 'OrdersController@update')->name('update');
    });

    // Payments
    Route::prefix('payments')->name('payments.')->group(function () {

        Route::get('/prepare-payment/{order}', 'PaymentsController@preparePayment')->name('prepare');
        Route::get('/complete', 'PaymentsController@redirect')->name('redirect');
    });


// Webshop
    Route::get('/', 'HomeController@index')->name('index');

// Categories
    Route::get('/{category}', 'CategoriesController@category')->name('category');

// Cart
    Route::prefix('cart')->name('cart.')->group(function () {
        Route::post('/store', 'CartController@store')->name('store');
    });

});


// Route::get('/dashboard', function () {
//     return view('dashboard');
// })->middleware(['auth'])->name('dashboard');


require __DIR__ . '/auth.php';

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

/**
 * Class Association
 * @package App\Models
 *
 * @property int id
 * @property string name
 * @property string email
 * @property string email_verified_at
 * @property string password
 * @property bool isAdmin
 * @property string remember_token
 * @property null|string created_at
 * @property null|string updated_at
 */
class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * @param \Illuminate\Database\Query\Builder $query
     * @param String $search
     * @return \Illuminate\Database\Query\Builder
     */
    public function scopeSearch($query, $search)
    {

        if (blank($search) || $search == 'all_users') {
            return $query;
        }

        return $query->where(function ($query) use ($search) {
            $query->where('name', 'like', '%' . $search . '%')
                ->orWhere('email', 'like', '%' . $search . '%');
        });
    }
}

app/Http/Controllers/Admin/UsersController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests\Users\StoreUserRequest;
use App\Models\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Hash;
use Illuminate\View\View;

class UsersController extends Controller
{
    /**
     * Show index
     *
     * @return View
     */
    public function index()
    {
        return view('admin.users.index')->with('users', User::all());
    }

    /**
     * Create
     *
     * @return View
     */
    public function create()
    {
        return view('admin.users.create');
    }

    /**
     * Edit
     *
     * @param int $id
     * @return View
     */
    public function edit(int $id)
    {
        return view('admin.products.edit')->with([

            'user' => User::find($id),
        ]);
    }

    /**
     * Store
     *
     * @param StoreUserRequest $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(StoreUserRequest $request)
    {
        $user = User::create([
            'name' => $request->name,
            'email' => $request->email,
            'password' => Hash::make($request->password),
        ]);

        return redirect()->route('users.index')->with('message', 'Gebruiker toegevoegd');
    }

    /**
     * Update
     *
     * @param StoreUserRequest $request
     * @param int $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(StoreUserRequest $request, int $id)
    {
        $user = User::find($id);
        $user->update($request->only($user->getFillable()));
        $user->save();

        return redirect()->route('users.index')->with('message', 'Gebruiker is gewijzigd');
    }

    /**
     * Delete
     *
     * @param int $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function delete(int $id)
    {
        User::find($id)->delete();

        return redirect()->route('users.index')->with('message', 'Gebruiker is verwijderd');
    }

    /**
     * Get index table
     *
     * @param String $search
     * @return string
     */
    public function getUsersIndexTable(string $search)
    {
        $users = User::search($search)
            ->orderBy('title', 'ASC')
            ->get();

        $html = view('admin.partials.users.index_table', compact('users'))->render();

        return $html;
    }
}

resources/views/admin/users/create.blade.php
@extends('layouts.dashboard')

@section('content')

    <div class="container mt-5 pb-3">
        <div class="row">
            <div class="col-12">
                <a href="{{route('users.index')}}"><i class="fas fa-arrow-left"></i> {{__('Terug')}}</a>
                <div class="card mt-3">
                    <div class="card-body">
                        <div class="card-title">
                            <h2>{{__('Gebruiker toevoegen')}}</h2>
                        </div>
                        <hr/>
                        <form action="{{route('users.store')}}" method="POST">
                            @csrf

                            <div class="form-group">
                                <label for="name">{{__('Naam')}}</label>
                                <input type="text" name="name" class="form-control @error('name') is-invalid @enderror"/>

                                @error('name')
                                <div class="alert alert-danger mt-3">{{ $message }}</div>
                                @enderror
                            </div>

                            <div class="form-group">
                                <label for="email">{{__('E-mailadres')}}</label>
                                <input type="email" name="email" class="form-control @error('email') is-invalid @enderror"/>

                                @error('email')
                                <div class="alert alert-danger mt-3">{{ $message }}</div>
                                @enderror
                            </div>

                            <div class="form-group">
                                <label for="password">{{__('Wachtwoord')}}</label>
                                <input type="password" name="password" class="form-control @error('password') is-invalid @enderror"/>

                                @error('password')
                                <div class="alert alert-danger mt-3">{{ $message }}</div>
                                @enderror
                            </div>

                            <div class="form-group text-right">
                                <button type="submit" class="btn btn-primary">{{__('Opslaan')}}</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/users/index.blade.php
@extends('layouts.dashboard')

@section('content')

    <div class="container mt-5 pb-3">

        @if (session('message'))
            <div class="row">
                <div class="col-12">
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        {{session('message')}}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                </div>
            </div>
        @endif

        <div class="row">
            <div class="col-4">
                <a href="{{route('dashboard')}}"><i class="fas fa-arrow-left"></i> {{__('Terug')}}</a>
            </div>
            <div class="col-8 mb-3 text-right">
                <a href="{{route('users.create')}}" class="btn btn-primary mb-3"><i class="fas fa-plus"></i> {{__('Gebruiker toevoegen')}}</a>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-xs-12 col-sm-4">
                                <div class="form-group">
                                    <label for="user-search">{{__('Zoeken')}}</label>
                                    <input type="text" name="user-search" class="form-control" id="allergy-search"/>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h2 class="card-title">{{__('Gebruikers')}}</h2>
                    </div>
                    <div class="card-body">
                        @include('admin.partials.users.index_table')
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection