routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware('hasAllowedIPAddress')->group(function () {


    Auth::routes();


    Route::prefix('/dashboard')->middleware('isAdminUser')->group(function () {
        Route::get('/', 'Admin\DashboardController@index')->name('dashboard');

        // Users
        Route::prefix('users')->name('users.')->group(function () {
            Route::get('/', 'Admin\UsersController@index')->name('index');
            Route::get('/create', 'Admin\UsersController@create')->name('create');
            Route::post('/store', 'Admin\UsersController@store')->name('store');
            Route::get('/edit/{id}', 'Admin\UsersController@edit')->name('edit');
            Route::post('/update/{id}', 'Admin\UsersController@update')->name('update');
            Route::get('/delete/{id}', 'Admin\UsersController@delete')->name('delete');
        });

        // Products
        Route::prefix('products')->name('products.')->group(function () {

            Route::get('/', 'Admin\ProductsController@index')->name('index');
            Route::get('/create', 'Admin\ProductsController@create')->name('create');
            Route::post('/store', 'Admin\ProductsController@store')->name('store');
            Route::get('/edit/{id}', 'Admin\ProductsController@edit')->name('edit');
            Route::post('/update/{id}', 'Admin\ProductsController@update')->name('update');
            Route::get('/delete/{id}', 'Admin\ProductsController@delete')->name('delete');
            Route::get('/get-products-index-table/{id}/{search}', 'Admin\ProductsController@getProductsIndexTable')->name('get_products_index_table');
        });

        // Categories
        Route::prefix('categories')->name('categories.')->group(function () {

            Route::get('/', 'Admin\CategoriesController@index')->name('index');
            Route::get('/create', 'Admin\CategoriesController@create')->name('create');
            Route::post('/store', 'Admin\CategoriesController@store')->name('store');
            Route::get('/edit/{id}', 'Admin\CategoriesController@edit')->name('edit');
            Route::post('/update/{id}', 'Admin\CategoriesController@update')->name('update');
            Route::get('/delete/{id}', 'Admin\CategoriesController@delete')->name('delete');
            Route::get('/get-categories-index-table/{search}', 'Admin\CategoriesController@getCategoriesIndexTable')->name('get_categories_index_table');
        });

        // Vats
        Route::prefix('vats')->name('vats.')->group(function () {

            Route::get('/', 'Admin\VatsController@index')->name('index');
            Route::get('/create', 'Admin\VatsController@create')->name('create');
            Route::post('/store', 'Admin\VatsController@store')->name('store');
            Route::get('/edit/{vat}', 'Admin\VatsController@edit')->name('edit');
            Route::post('/update/{vat}', 'Admin\VatsController@update')->name('update');
            Route::get('/delete/{vat}', 'Admin\VatsController@delete')->name('delete');
            Route::get('/get-vats-index-table/{search}', 'Admin\VatsController@getVatsIndexTable')->name('get_vats_index_table');
        });

        Route::prefix('orders')->name('orders.')->group(function () {
            Route::get('/', 'Admin\OrdersController@index')->name('index');
        });

        // Allergies
        Route::prefix('allergies')->name('allergies.')->group(function () {

            Route::get('/', 'Admin\AllergiesController@index')->name('index');
            Route::get('/create', 'Admin\AllergiesController@create')->name('create');
            Route::post('/store', 'Admin\AllergiesController@store')->name('store');
            Route::get('/edit/{allergy}', 'Admin\AllergiesController@edit')->name('edit');
            Route::post('/update/{allergy}', 'Admin\AllergiesController@update')->name('update');
            Route::get('/delete/{allergy}', 'Admin\AllergiesController@delete')->name('delete');
            Route::get('/get-index-table/{search}', 'Admin\AllergiesController@getIndexTable')->name('get_index_table');
        });

        // Discounts
        Route::prefix('discounts')->name('discounts.')->group(function () {

            Route::get('/', 'Admin\DiscountsController@index')->name('index');
            Route::get('/create', 'Admin\DiscountsController@create')->name('create');
            Route::post('/store/{product}', 'Admin\DiscountsController@store')->name('store');
            Route::get('/edit/{product}', 'Admin\DiscountsController@edit')->name('edit');
            Route::post('/update/{product}', 'Admin\DiscountsController@update')->name('update');
        });
    });

    // Orders
    Route::prefix('orders')->name('orders.')->group(function () {

        Route::get('/success/{order}', 'OrdersController@success')->name('success');
        Route::post('/store', 'OrdersController@store')->name('store');
        Route::post('/update/{order}', 'OrdersController@update')->name('update');
    });

    // Payments
    Route::prefix('payments')->name('payments.')->group(function () {

        Route::get('/prepare-payment/{order}', 'PaymentsController@preparePayment')->name('prepare');
        Route::get('/complete', 'PaymentsController@redirect')->name('redirect');
    });


// Webshop
    Route::get('/', 'HomeController@index')->name('index');

// Categories
    Route::get('/{category}', 'CategoriesController@category')->name('category');

// Cart
    Route::prefix('cart')->name('cart.')->group(function () {
        Route::post('/store', 'CartController@store')->name('store');
    });

});


// Route::get('/dashboard', function () {
//     return view('dashboard');
// })->middleware(['auth'])->name('dashboard');


require __DIR__ . '/auth.php';

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">

        <!-- Styles -->
        <link rel="stylesheet" href="{{ asset('css/app.css') }}">

        <!-- Scripts -->
        <script src="{{ asset('js/app.js') }}" defer></script>
    </head>
    <body class="font-sans antialiased">
        <div class="min-h-screen bg-gray-100">
            @include('layouts.navigation')

            <!-- Page Heading -->
            <header class="bg-white shadow">
                <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
                    {{ $header }}
                </div>
            </header>

            <!-- Page Content -->
            <main>
                {{ $slot }}
            </main>
        </div>
    </body>
</html>

resources/views/layouts/auth.blade.php
<!doctype html> 
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <!-- Google Tag Manager -->
    <script>
        (function(w, d, s, l, i) {
            w[l] = w[l] || [];
            w[l].push({
                'gtm.start': new Date().getTime(),
                event: 'gtm.js'
            });
            var f = d.getElementsByTagName(s)[0],
                j = d.createElement(s),
                dl = l != 'dataLayer' ? '&l=' + l : '';
            j.async = true;
            j.src =
                'https://www.googletagmanager.com/gtm.js?id=' + i + dl;
            f.parentNode.insertBefore(j, f);
        })(window, document, 'script', 'dataLayer', 'GTM-WFLLVZ');
    </script>
    <!-- End Google Tag Manager -->

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{ asset('css/sidebar.css') }}" rel="stylesheet">
</head>

<body>
    <div id="app">
        <section>
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        @yield('content')
                    </div>
                </div>
            </div>
        </section>
    </div>
</body>

</html>

resources/views/layouts/dashboard.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <!-- Google Tag Manager -->
    {{-- <script>
        (function(w, d, s, l, i) {
            w[l] = w[l] || [];
            w[l].push({
                'gtm.start': new Date().getTime(),
                event: 'gtm.js'
            });
            var f = d.getElementsByTagName(s)[0],
                j = d.createElement(s),
                dl = l != 'dataLayer' ? '&l=' + l : '';
            j.async = true;
            j.src =
                'https://www.googletagmanager.com/gtm.js?id=' + i + dl;
            f.parentNode.insertBefore(j, f);
        })(window, document, 'script', 'dataLayer', 'GTM-WFLLVZ');
    </script> --}}
    <!-- End Google Tag Manager -->

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>
    <script src="{{ asset('js/ckeditor/ckeditor.js') }}" defer></script>
    <script src="{{ asset('js/ckeditor/adapters/jquery.js') }}" defer></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/bootstrap-select.min.js" defer></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{ asset('css/sidebar.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/css/bootstrap-select.min.css">
</head>

<body class="dashboard">
    <div id="app">
        <div class="sidebar closed">
            <i class="fas fa-times"></i>
            <div class="logo-details pt-4">
                <i class='bx bxl-c-plus-plus'></i>
                <span class="logo_name">Bakkerij zwarthoed</span>
            </div>
            <ul class="nav-links">
                <li>
                    <a href="{{ route('dashboard') }}">
                        <i class="fas fa-tachometer-alt"></i>
                        <span class="link_name">{{__('Dashboard')}}</span>
                    </a>
                </li>
                <li>
                    <div class="icon-link">
                        <a href="{{ route('products.index') }}">
                            <i class="fas fa-box"></i>
                            <span class="link_name">{{__('Producten')}}</span>
                        </a>
                        <i class='fas fa-chevron-down'></i>
                    </div>
                    <ul class="sub-menu">
                        <li><a class="link_name" href="#">{{__('Producten')}}</a></li>
                        <li><a href="{{ route('products.index') }}">{{__('Alle producten')}}</a></li>
                        <li><a href="{{ route('products.create') }}">{{__('Product toevoegen')}}</a></li>
                    </ul>
                </li>
                <li>
                    <div class="icon-link">
                        <a href="{{ route('categories.index') }}">
                            <i class="fas fa-th-large"></i>
                            <span class="link_name">{{__('Categorieën')}}</span>
                        </a>
                        <i class='fas fa-chevron-down'></i>
                    </div>
                    <ul class="sub-menu">
                        <li><a class="link_name" href="#">{{__('Categorieën')}}</a></li>
                        <li><a href="{{ route('categories.index') }}">{{__('Alle categorieën')}}</a></li>
                        <li><a href="{{ route('categories.create') }}">{{__('Categorie toevoegen')}}</a></li>
                    </ul>
                </li>
                <li>
                    <div class="icon-link">
                        <a href="{{ route('categories.index') }}">
                            <i class="fas fa-tags"></i>
                            <span class="link_name">{{__('Aanbiedingen')}}</span>
                        </a>
                        <i class='fas fa-chevron-down'></i>
                    </div>
                    <ul class="sub-menu">
                        <li><a class="link_name" href="#">{{__('Aanbiedingen')}}</a></li>
                        <li><a href="{{ route('categories.index') }}">{{__('Alle aanbiedingen')}}</a></li>
                        <li><a href="{{ route('categories.create') }}">{{__('Aanbieding toevoegen')}}</a></li>
                    </ul>
                </li>
                <li>
                    <div class="icon-link">
                        <a href="{{ route('allergies.index') }}">
                            <i class="fas fa-allergies"></i>
                            <span class="link_name">{{__('Allergieën')}}</span>
                        </a>
                        <i class='fas fa-chevron-down'></i>
                    </div>
                    <ul class="sub-menu">
                        <li><a class="link_name" href="#">{{__('Allergieën')}}</a></li>
                        <li><a href="{{ route('allergies.index') }}">{{__('Alle allergieën')}}</a></li>
                        <li><a href="{{ route('allergies.create') }}">{{__('Allergie toevoegen')}}</a></li>
                    </ul>
                </li>
                <li>
                    <div class="icon-link">
                        <a href="{{ route('orders.index') }}">
                            <i class="fas fa-euro-sign"></i>
                            <span class="link_name">{{__('Bestellingen')}}</span>
                        </a>
                        <i class='fas fa-chevron-down'></i>
                    </div>
                    <ul class="sub-menu">
                        <li><a class="link_name" href="#">{{__('Bestellingen')}}</a></li>
                        <li><a href="{{ route('orders.index') }}">{{__('Alle bestellingen')}}</a></li>
                    </ul>
                </li>
                <li>
                    <div class="icon-link">
                        <a href="{{ route('vats.index') }}">
                            <i class="fas fa-percent"></i>
                            <span class="link_name">{{__('BTW')}}</span>
                        </a>
                        <i class='fas fa-chevron-down'></i>
                    </div>
                    <ul class="sub-menu">
                        <li><a class="link_name" href="#">{{__('BTW')}}</a></li>
                        <li><a href="{{ route('vats.index') }}">{{__('BTW tarieven')}}</a></li>
                        <li><a href="{{ route('vats.create') }}">{{__('BTW tarief toevoegen')}}</a></li>
                    </ul>
                </li>
                <li>
                    <div class="icon-link">
                        <a href="{{ route('users.index') }}">
                            <i class="fas fa-users"></i>
                            <span class="link_name">{{__('Gebruikers')}}</span>
                        </a>
                        <i class='fas fa-chevron-down'></i>
                    </div>
                    <ul class="sub-menu">
                        <li><a class="link_name" href="#">{{__('Gebruikers')}}</a></li>
                        <li><a href="{{ route('users.index') }}">{{__('Alle gebruikers')}}</a></li>
                        <li><a href="{{ route('users.create') }}">{{__('Gebruiker toevoegen')}}</a></li>
                    </ul>
                </li>
            </ul>
        </div>
        <section class="home-section">
            <div class="home-content">
                <i class="fas fa-bars"></i>
                <span class="text pl-1">
                    <img src="{{asset('images/logo.png')}}" alt="Bakkerij zwarthoed" class="img-fluid" style="max-height: 60px;"/>
                </span>
            </div>
            @yield('content')
        </section>
    </div>
</body>

</html>

resources/views/layouts/guest.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">

        <!-- Styles -->
        <link rel="stylesheet" href="{{ asset('css/app.css') }}">

        <!-- Scripts -->
        <script src="{{ asset('js/app.js') }}" defer></script>
    </head>
    <body>
        <div class="font-sans text-gray-900 antialiased">
            {{ $slot }}
        </div>
    </body>
</html>

resources/views/layouts/navigation.blade.php
<nav x-data="{ open: false }" class="bg-white border-b border-gray-100">
    <!-- Primary Navigation Menu -->
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="flex justify-between h-16">
            <div class="flex">
                <!-- Logo -->
                <div class="flex-shrink-0 flex items-center">
                    <a href="{{ route('dashboard') }}">
                        <x-application-logo class="block h-10 w-auto fill-current text-gray-600" />
                    </a>
                </div>

                <!-- Navigation Links -->
                <div class="hidden space-x-8 sm:-my-px sm:ml-10 sm:flex">
                    <x-nav-link :href="route('dashboard')" :active="request()->routeIs('dashboard')">
                        {{ __('Dashboard') }}
                    </x-nav-link>
                </div>
            </div>

            <!-- Settings Dropdown -->
            <div class="hidden sm:flex sm:items-center sm:ml-6">
                <x-dropdown align="right" width="48">
                    <x-slot name="trigger">
                        <button class="flex items-center text-sm font-medium text-gray-500 hover:text-gray-700 hover:border-gray-300 focus:outline-none focus:text-gray-700 focus:border-gray-300 transition duration-150 ease-in-out">
                            <div>{{ Auth::user()->name }}</div>

                            <div class="ml-1">
                                <svg class="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                                    <path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd" />
                                </svg>
                            </div>
                        </button>
                    </x-slot>

                    <x-slot name="content">
                        <!-- Authentication -->
                        <form method="POST" action="{{ route('logout') }}">
                            @csrf

                            <x-dropdown-link :href="route('logout')"
                                    onclick="event.preventDefault();
                                                this.closest('form').submit();">
                                {{ __('Log Out') }}
                            </x-dropdown-link>
                        </form>
                    </x-slot>
                </x-dropdown>
            </div>

            <!-- Hamburger -->
            <div class="-mr-2 flex items-center sm:hidden">
                <button @click="open = ! open" class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:bg-gray-100 focus:text-gray-500 transition duration-150 ease-in-out">
                    <svg class="h-6 w-6" stroke="currentColor" fill="none" viewBox="0 0 24 24">
                        <path :class="{'hidden': open, 'inline-flex': ! open }" class="inline-flex" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
                        <path :class="{'hidden': ! open, 'inline-flex': open }" class="hidden" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                    </svg>
                </button>
            </div>
        </div>
    </div>

    <!-- Responsive Navigation Menu -->
    <div :class="{'block': open, 'hidden': ! open}" class="hidden sm:hidden">
        <div class="pt-2 pb-3 space-y-1">
            <x-responsive-nav-link :href="route('dashboard')" :active="request()->routeIs('dashboard')">
                {{ __('Dashboard') }}
            </x-responsive-nav-link>
        </div>

        <!-- Responsive Settings Options -->
        <div class="pt-4 pb-1 border-t border-gray-200">
            <div class="px-4">
                <div class="font-medium text-base text-gray-800">{{ Auth::user()->name }}</div>
                <div class="font-medium text-sm text-gray-500">{{ Auth::user()->email }}</div>
            </div>

            <div class="mt-3 space-y-1">
                <!-- Authentication -->
                <form method="POST" action="{{ route('logout') }}">
                    @csrf

                    <x-responsive-nav-link :href="route('logout')"
                            onclick="event.preventDefault();
                                        this.closest('form').submit();">
                        {{ __('Log Out') }}
                    </x-responsive-nav-link>
                </form>
            </div>
        </div>
    </div>
</nav>

resources/views/layouts/pagination.blade.php
@if ($paginator->lastPage() > 1)
    <ul >
        <li class="{{ ($paginator->currentPage() == 1) ? ' disabled' : '' }} inline border-t border-b border-l border-brand-light px-3 py-2 no-underline">
            <a href="{{ $paginator->url(1) }}"><<</a>
        </li>
        @for ($i = 1; $i <= $paginator->lastPage(); $i++)
            <li class="{{ ($paginator->currentPage() == $i) ? ' text-green-500' : '' }} inline border-t border-b border-l border-brand-light px-3 py-2 no-underline">
                <a href="{{ $paginator->url($i) }}">{{ $i }}</a>
            </li>
        @endfor
        <li class="{{ ($paginator->currentPage() == $paginator->lastPage()) ? ' disabled' : '' }} inline border-t border-b border-r border-l border-brand-light px-3 py-2 no-underline">
            <a href="{{ $paginator->url($paginator->currentPage()+1) }}" >>></a>
        </li>
    </ul>
@endif

resources/views/layouts/site.blade.php
<!doctype html> 
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <!-- Google Tag Manager -->
    {{-- <script>
        (function(w, d, s, l, i) {
            w[l] = w[l] || [];
            w[l].push({
                'gtm.start': new Date().getTime(),
                event: 'gtm.js'
            });
            var f = d.getElementsByTagName(s)[0],
                j = d.createElement(s),
                dl = l != 'dataLayer' ? '&l=' + l : '';
            j.async = true;
            j.src =
                'https://www.googletagmanager.com/gtm.js?id=' + i + dl;
            f.parentNode.insertBefore(j, f);
        })(window, document, 'script', 'dataLayer', 'GTM-WFLLVZ');
    </script> --}}
    <!-- End Google Tag Manager -->

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>
    <script src="{{ asset('js/ckeditor/ckeditor.js') }}" defer></script>
    <script src="{{ asset('js/ckeditor/adapters/jquery.js') }}" defer></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/bootstrap-select.min.js" defer></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{ asset('css/sidebar.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/css/bootstrap-select.min.css">

    @livewireStyles
</head>

<body class="site">
    @if (session('message'))
        <div class="row">
            <div class="col-12">
                <div class="alert alert-{{session('status')}} alert-dismissible fade show" role="alert">
                    {{session('message')}}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            </div>
        </div>
    @endif
    <div id="app">
        @include('site.navigation')
        @yield('content')
        @include('site.footer')
    </div>
    @livewireScripts
</body>

</html>