routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware('hasAllowedIPAddress')->group(function () {


    Auth::routes();


    Route::prefix('/dashboard')->middleware('isAdminUser')->group(function () {
        Route::get('/', 'Admin\DashboardController@index')->name('dashboard');

        // Users
        Route::prefix('users')->name('users.')->group(function () {
            Route::get('/', 'Admin\UsersController@index')->name('index');
            Route::get('/create', 'Admin\UsersController@create')->name('create');
            Route::post('/store', 'Admin\UsersController@store')->name('store');
            Route::get('/edit/{id}', 'Admin\UsersController@edit')->name('edit');
            Route::post('/update/{id}', 'Admin\UsersController@update')->name('update');
            Route::get('/delete/{id}', 'Admin\UsersController@delete')->name('delete');
        });

        // Products
        Route::prefix('products')->name('products.')->group(function () {

            Route::get('/', 'Admin\ProductsController@index')->name('index');
            Route::get('/create', 'Admin\ProductsController@create')->name('create');
            Route::post('/store', 'Admin\ProductsController@store')->name('store');
            Route::get('/edit/{id}', 'Admin\ProductsController@edit')->name('edit');
            Route::post('/update/{id}', 'Admin\ProductsController@update')->name('update');
            Route::get('/delete/{id}', 'Admin\ProductsController@delete')->name('delete');
            Route::get('/get-products-index-table/{id}/{search}', 'Admin\ProductsController@getProductsIndexTable')->name('get_products_index_table');
        });

        // Categories
        Route::prefix('categories')->name('categories.')->group(function () {

            Route::get('/', 'Admin\CategoriesController@index')->name('index');
            Route::get('/create', 'Admin\CategoriesController@create')->name('create');
            Route::post('/store', 'Admin\CategoriesController@store')->name('store');
            Route::get('/edit/{id}', 'Admin\CategoriesController@edit')->name('edit');
            Route::post('/update/{id}', 'Admin\CategoriesController@update')->name('update');
            Route::get('/delete/{id}', 'Admin\CategoriesController@delete')->name('delete');
            Route::get('/get-categories-index-table/{search}', 'Admin\CategoriesController@getCategoriesIndexTable')->name('get_categories_index_table');
        });

        // Vats
        Route::prefix('vats')->name('vats.')->group(function () {

            Route::get('/', 'Admin\VatsController@index')->name('index');
            Route::get('/create', 'Admin\VatsController@create')->name('create');
            Route::post('/store', 'Admin\VatsController@store')->name('store');
            Route::get('/edit/{vat}', 'Admin\VatsController@edit')->name('edit');
            Route::post('/update/{vat}', 'Admin\VatsController@update')->name('update');
            Route::get('/delete/{vat}', 'Admin\VatsController@delete')->name('delete');
            Route::get('/get-vats-index-table/{search}', 'Admin\VatsController@getVatsIndexTable')->name('get_vats_index_table');
        });

        Route::prefix('orders')->name('orders.')->group(function () {
            Route::get('/', 'Admin\OrdersController@index')->name('index');
        });

        // Allergies
        Route::prefix('allergies')->name('allergies.')->group(function () {

            Route::get('/', 'Admin\AllergiesController@index')->name('index');
            Route::get('/create', 'Admin\AllergiesController@create')->name('create');
            Route::post('/store', 'Admin\AllergiesController@store')->name('store');
            Route::get('/edit/{allergy}', 'Admin\AllergiesController@edit')->name('edit');
            Route::post('/update/{allergy}', 'Admin\AllergiesController@update')->name('update');
            Route::get('/delete/{allergy}', 'Admin\AllergiesController@delete')->name('delete');
            Route::get('/get-index-table/{search}', 'Admin\AllergiesController@getIndexTable')->name('get_index_table');
        });

        // Discounts
        Route::prefix('discounts')->name('discounts.')->group(function () {

            Route::get('/', 'Admin\DiscountsController@index')->name('index');
            Route::get('/create', 'Admin\DiscountsController@create')->name('create');
            Route::post('/store/{product}', 'Admin\DiscountsController@store')->name('store');
            Route::get('/edit/{product}', 'Admin\DiscountsController@edit')->name('edit');
            Route::post('/update/{product}', 'Admin\DiscountsController@update')->name('update');
        });
    });

    // Orders
    Route::prefix('orders')->name('orders.')->group(function () {

        Route::get('/success/{order}', 'OrdersController@success')->name('success');
        Route::post('/store', 'OrdersController@store')->name('store');
        Route::post('/update/{order}', 'OrdersController@update')->name('update');
    });

    // Payments
    Route::prefix('payments')->name('payments.')->group(function () {

        Route::get('/prepare-payment/{order}', 'PaymentsController@preparePayment')->name('prepare');
        Route::get('/complete', 'PaymentsController@redirect')->name('redirect');
    });


// Webshop
    Route::get('/', 'HomeController@index')->name('index');

// Categories
    Route::get('/{category}', 'CategoriesController@category')->name('category');

// Cart
    Route::prefix('cart')->name('cart.')->group(function () {
        Route::post('/store', 'CartController@store')->name('store');
    });

});


// Route::get('/dashboard', function () {
//     return view('dashboard');
// })->middleware(['auth'])->name('dashboard');


require __DIR__ . '/auth.php';

app/Models/Category.php
<?php
namespace App\Models;

use Carbon\Carbon;
use App\Models\QuestionList;
use App\Models\Question;
use App\Models\Participant;
use Cviebrock\EloquentSluggable\Sluggable;
use Illuminate\Database\Eloquent\Model;

/**
 * Class Association
 * @package App\Models
 *
 * @property int            id
 * @property string         slug
 * @property string         title
 * @property string         description
 * @property string         image
 * @property null|Carbon    created_at
 * @property null|Carbon    updated_at
 */
class Category extends Model {

  use Sluggable;

    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'categories';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'slug',
        'title',
        'description',
        'image',
    ];


    /*
      |-------------------------------------------------------------------------
      | Relationships
      |-------------------------------------------------------------------------
     */

    /**
     * Get the product
     */
    public function products()
    {
        return $this->hasMany(Product::class);
    }


    /*
      |-------------------------------------------------------------------------
      | Query scopes
      |-------------------------------------------------------------------------
     */

    /**
     * @param \Illuminate\Database\Query\Builder $query
     * @param String $search
     * @return \Illuminate\Database\Query\Builder
     */
    public function scopeSearch($query, $search) {

      if (blank($search) || $search == 'all_categories') {

          return $query;
      }

      return $query->where(function ($query) use ($search) {

          $query->where('title', 'like', '%' . $search . '%')
              ->orWhere('description', 'like', '%' . $search . '%');
      });
  }


    /*
      |-------------------------------------------------------------------------
      | Accessors
      |-------------------------------------------------------------------------
     */

     /**
      * return slug
      */
    public function sluggable() : array
    {
        return [
            'slug' => [
                'source' => 'title'
            ]
        ];
    }

    /**
     * Get the route key for the model.
     *
     * @return string
     */
    public function getRouteKeyName(): string
    {
        return 'slug';
    }
}

app/Http/Controllers/Admin/CategoriesController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Models\Category;
use App\Models\Product;
use App\Http\Requests\Categories\StoreCategoryRequest;
use App\Http\Controllers\Controller;

class CategoriesController extends Controller
{
    // Show index
    public function index()
    {
        return view('admin.categories.index')->with('categories', Category::orderBy('title', 'ASC')->get());
    }

    /**
     * Create new category
     *
     * @return \Illuminate\View\View
     */
    public function create()
    {
        return view('admin.categories.create');
    }

    /**
     * Edit category
     *
     * @param int $id
     * 
     * @return \Illuminate\View\View
     */
    public function edit(int $id)
    {
        return view('admin.categories.edit')->with('category', Category::find($id));
    }

    /**
     * Store new category
     *
     * @param StoreCategoryRequest $request
     * @return \Illuminate\View\View
     */
    public function store(StoreCategoryRequest $request)
    {
        $category = new Category();
        $category->fill($request->only($category->getFillable()));
        $category->save();

        if ($request->hasFile('image') && $request->file('image')->isValid()) {

            $path = request()->file('image')->storeAs('images/categories', $category->title.'_'.$category->id.'.'.$request->file('image')->getClientOriginalExtension(), 'public');
            
            $category->image = $path;
            $category->save();
        }
        
        return redirect()->route('categories.index')->with('message', 'Categorie toegevoegd');
    }

    /**
     * Update category
     *
     * @param StoreCategoryRequest $request
     * @param int $id
     */
    public function update(StoreCategoryRequest $request, int $id)
    {
        $category = Category::find($id);
        $category->update($request->only($category->getFillable()));
        $category->save();

        if ($request->hasFile('image') && $request->file('image')->isValid()) {

            $path = request()->file('image')->storeAs('images/categories', $category->title.'_'.$category->id.'.'.$request->file('image')->getClientOriginalExtension(), 'public');
            
            $category->image = $path;
            $category->save();
        }
        
        return redirect()->route('categories.index')->with('message', 'Categorie is gewijzigd');
    }


    /**
     * Delete category
     *
     * @param int $id
     */
    public function delete(int $id)
    {
        Product::where('category_id', $id)->update(['category_id' => null]);
        Category::find($id)->delete();

        return redirect()->route('categories.index')->with('message', 'Categorie is verwijderd');
    }

    /**
     * Get categories index table
     *
     * @param String $search
     */
    public function getCategoriesIndexTable(String $search)
    {
        $categories = Category::search($search)->orderBy('title', 'ASC')->get();
                    
        $html = view('admin.partials.categories.index_table', compact('categories'))->render();

        return $html;
    }
}

app/Http/Controllers/CategoriesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Category;
use App\Models\Product;
use App\Http\Controllers\Controller;

class CategoriesController extends Controller
{
    // Show index
    public function index()
    {
        return view('site.categories.index')->with('categories', Category::orderBy('title', 'ASC')->get());
    }

    // show category detail page
    public function category(Category $category)
    {
        $category->load(['products']);

        return view('site.categories.category')->with([
            'category'      => $category,
            'categories'    => Category::orderBy('title', 'ASC')->get(),
        ]);
    }
}

resources/views/admin/categories/create.blade.php
@extends('layouts.dashboard')

@section('content')

    <div class="container mt-5 pb-3">
        <div class="row">
            <div class="col-12">
                <a href="{{route('categories.index')}}"><i class="fas fa-arrow-left"></i> {{__('Terug')}}</a>
                <div class="card mt-3">
                    <div class="card-body">
                        <div class="card-title">
                            <h2>{{__('Categorie toevoegen')}}</h2>
                        </div>
                        <hr/>
                        <form action="{{route('categories.store')}}" method="POST" enctype="multipart/form-data">
                            @csrf
        
                            <div class="form-group">
                                <label for="title">{{__('Titel')}}</label>
                                <input type="text" name="title" class="form-control @error('title') is-invalid @enderror"/>

                                @error('title')
                                    <div class="alert alert-danger mt-3">{{ $message }}</div>
                                @enderror
                            </div>
        
                            <div class="form-group">
                                <label for="description">{{__('Beschrijving')}}</label>
                                <textarea name="description" cols="30" rows="10" class="form-control ckeditor @error('description') is-invalid @enderror"></textarea>

                                @error('description')
                                    <div class="alert alert-danger mt-3">{{ $message }}</div>
                                @enderror
                            </div>

                            <div class="form-group">
                                <label for="image">{{__('Afbeelding')}}</label>
                                <input type="file" name="image" class="form-control-file @error('description') is-invalid @enderror" id="image">

                                @error('image')
                                    <div class="alert alert-danger mt-3">{{ $message }}</div>
                                @enderror
                            </div>
        
                            <div class="form-group text-right">
                                <button type="submit" class="btn btn-primary">Opslaan</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/categories/edit.blade.php
@extends('layouts.dashboard')

@section('content')

    <div class="container mt-5 pb-3">
        <div class="row">
            <div class="col-12">
                <a href="{{route('categories.index')}}"><i class="fas fa-arrow-left"></i> {{__('Terug')}}</a>
                <div class="card mt-3">
                    <div class="card-body">
                        <div class="card-title">
                            <h2>{{$category->title}}</h2>
                        </div>
                        <hr/>
                        <form action="{{route('categories.update', $category->id)}}" method="POST" enctype="multipart/form-data">
                            @csrf
        
                            <div class="form-group">
                                <label for="title">Titel</label>
                                <input type="text" name="title" class="form-control @error('title') is-invalid @enderror" value="{{$category->title}}"/>

                                @error('title')
                                    <div class="alert alert-danger mt-3">{{ $message }}</div>
                                @enderror
                            </div>
        
                            <div class="form-group">
                                <label for="description">{{__('Beschrijving')}}</label>
                                <textarea name="description" cols="30" rows="10" class="form-control ckeditor @error('description') is-invalid @enderror">{!!$category->description!!}</textarea>

                                @error('description')
                                    <div class="alert alert-danger mt-3">{{ $message }}</div>
                                @enderror
                            </div>

                            <div class="form-group">
                                <label for="image">{{__('Afbeelding')}}</label>
                                <input type="file" name="image" class="form-control-file @error('description') is-invalid @enderror" id="image">

                                @if (!empty($category->image))

                                    <img src="/{{$category->image}}" alt="{{$category->title}}" class="img-fluid mt-3"/>
                                @endif

                                @error('image')
                                    <div class="alert alert-danger mt-3">{{ $message }}</div>
                                @enderror
                            </div>
        
                            <div class="form-group text-right">
                                <button type="submit" class="btn btn-primary">{{__('Opslaan')}}</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/categories/index.blade.php
@extends('layouts.dashboard')

@section('content')

<div class="container mt-5 pb-3">

    @if (session('message'))
        <div class="row">
            <div class="col-12">
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    {{session('message')}}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            </div>
        </div>
    @endif

    <div class="row">
        <div class="col-4">
            <a href="{{route('dashboard')}}"><i class="fas fa-arrow-left"></i> {{__('Terug')}}</a>
        </div>
        <div class="col-8 mb-3 text-right">
            <a href="{{route('categories.create')}}" class="btn btn-primary mb-3"><i class="fas fa-plus"></i> {{__('Categorie toevoegen')}}</a>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-xs-12 col-sm-4">
                            <div class="form-group">
                                <label for="category-search">{{__('Zoeken')}}</label>
                                <input type="text" name="category-search" class="form-control" id="category-search"/>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h2 class="card-title">{{__('Categorieën')}}</h2>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table categories-table">
                            <thead>
                                <tr>
                                    <th></th>
                                    <th>{{__('Titel')}}</th>
                                    <th>{{__('Beschrijving')}}</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($categories as $category)

                                    <tr>
                                        <td>
                                            @if (!empty($category->image))

                                                <img src="/{{ $category->image }}" alt="{{$category->title}}" class="img-fluid"/>
                                            @endif
                                        </td>
                                        <td>
                                            <a href="{{route('categories.edit', $category->id,)}}">{{$category->title}}</a>
                                        </td>
                                        <td>{!!$category->description!!}</td>
                                        <td>
                                            <a href="#" type="button" data-toggle="modal" data-target="#delete-category-modal-{{$category->id}}" class="text-danger"><i class="fas fa-trash"></i></a>

                                            <div id="delete-category-modal-{{$category->id}}" tabindex="-1" role="dialog" aria-hidden="true" class="modal fade">
                                                <div role="document" class="modal-dialog">
                                                    <div class="modal-content">
                                                        <div class="modal-header">
                                                            <h5 id="exampleModalLabel" class="modal-title">{{__('Categorie verwijderen')}}?</h5>
                                                            <button type="button" data-dismiss="modal" aria-label="Close" class="close">
                                                                <span aria-hidden="true">×</span>
                                                            </button>
                                                        </div>
                                                        <div class="modal-body">
                                                            <p>
                                                                {{__('Weet u zeker dat u')}} <b>{{$category->title}}</b> {{__('wilt verwijderen?')}}?
                                                            </p>
                                                            @if (!empty($category->image))

                                                                <img src="/{{$category->image}}" alt="{{$category->title}}" class="img-fluid">
                                                            @endif
                                                        </div>
                                                        <div class="modal-footer">
                                                            <button type="button" data-dismiss="modal" class="btn btn-secondary">{{__('Annuleren')}}</button>
                                                            <a href="{{route('categories.delete', $category->id)}}" class="btn btn-danger">{{__('Verwijderen')}}</a>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection