routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware('hasAllowedIPAddress')->group(function () {


    Auth::routes();


    Route::prefix('/dashboard')->middleware('isAdminUser')->group(function () {
        Route::get('/', 'Admin\DashboardController@index')->name('dashboard');

        // Users
        Route::prefix('users')->name('users.')->group(function () {
            Route::get('/', 'Admin\UsersController@index')->name('index');
            Route::get('/create', 'Admin\UsersController@create')->name('create');
            Route::post('/store', 'Admin\UsersController@store')->name('store');
            Route::get('/edit/{id}', 'Admin\UsersController@edit')->name('edit');
            Route::post('/update/{id}', 'Admin\UsersController@update')->name('update');
            Route::get('/delete/{id}', 'Admin\UsersController@delete')->name('delete');
        });

        // Products
        Route::prefix('products')->name('products.')->group(function () {

            Route::get('/', 'Admin\ProductsController@index')->name('index');
            Route::get('/create', 'Admin\ProductsController@create')->name('create');
            Route::post('/store', 'Admin\ProductsController@store')->name('store');
            Route::get('/edit/{id}', 'Admin\ProductsController@edit')->name('edit');
            Route::post('/update/{id}', 'Admin\ProductsController@update')->name('update');
            Route::get('/delete/{id}', 'Admin\ProductsController@delete')->name('delete');
            Route::get('/get-products-index-table/{id}/{search}', 'Admin\ProductsController@getProductsIndexTable')->name('get_products_index_table');
        });

        // Categories
        Route::prefix('categories')->name('categories.')->group(function () {

            Route::get('/', 'Admin\CategoriesController@index')->name('index');
            Route::get('/create', 'Admin\CategoriesController@create')->name('create');
            Route::post('/store', 'Admin\CategoriesController@store')->name('store');
            Route::get('/edit/{id}', 'Admin\CategoriesController@edit')->name('edit');
            Route::post('/update/{id}', 'Admin\CategoriesController@update')->name('update');
            Route::get('/delete/{id}', 'Admin\CategoriesController@delete')->name('delete');
            Route::get('/get-categories-index-table/{search}', 'Admin\CategoriesController@getCategoriesIndexTable')->name('get_categories_index_table');
        });

        // Vats
        Route::prefix('vats')->name('vats.')->group(function () {

            Route::get('/', 'Admin\VatsController@index')->name('index');
            Route::get('/create', 'Admin\VatsController@create')->name('create');
            Route::post('/store', 'Admin\VatsController@store')->name('store');
            Route::get('/edit/{vat}', 'Admin\VatsController@edit')->name('edit');
            Route::post('/update/{vat}', 'Admin\VatsController@update')->name('update');
            Route::get('/delete/{vat}', 'Admin\VatsController@delete')->name('delete');
            Route::get('/get-vats-index-table/{search}', 'Admin\VatsController@getVatsIndexTable')->name('get_vats_index_table');
        });

        Route::prefix('orders')->name('orders.')->group(function () {
            Route::get('/', 'Admin\OrdersController@index')->name('index');
        });

        // Allergies
        Route::prefix('allergies')->name('allergies.')->group(function () {

            Route::get('/', 'Admin\AllergiesController@index')->name('index');
            Route::get('/create', 'Admin\AllergiesController@create')->name('create');
            Route::post('/store', 'Admin\AllergiesController@store')->name('store');
            Route::get('/edit/{allergy}', 'Admin\AllergiesController@edit')->name('edit');
            Route::post('/update/{allergy}', 'Admin\AllergiesController@update')->name('update');
            Route::get('/delete/{allergy}', 'Admin\AllergiesController@delete')->name('delete');
            Route::get('/get-index-table/{search}', 'Admin\AllergiesController@getIndexTable')->name('get_index_table');
        });

        // Discounts
        Route::prefix('discounts')->name('discounts.')->group(function () {

            Route::get('/', 'Admin\DiscountsController@index')->name('index');
            Route::get('/create', 'Admin\DiscountsController@create')->name('create');
            Route::post('/store/{product}', 'Admin\DiscountsController@store')->name('store');
            Route::get('/edit/{product}', 'Admin\DiscountsController@edit')->name('edit');
            Route::post('/update/{product}', 'Admin\DiscountsController@update')->name('update');
        });
    });

    // Orders
    Route::prefix('orders')->name('orders.')->group(function () {

        Route::get('/success/{order}', 'OrdersController@success')->name('success');
        Route::post('/store', 'OrdersController@store')->name('store');
        Route::post('/update/{order}', 'OrdersController@update')->name('update');
    });

    // Payments
    Route::prefix('payments')->name('payments.')->group(function () {

        Route::get('/prepare-payment/{order}', 'PaymentsController@preparePayment')->name('prepare');
        Route::get('/complete', 'PaymentsController@redirect')->name('redirect');
    });


// Webshop
    Route::get('/', 'HomeController@index')->name('index');

// Categories
    Route::get('/{category}', 'CategoriesController@category')->name('category');

// Cart
    Route::prefix('cart')->name('cart.')->group(function () {
        Route::post('/store', 'CartController@store')->name('store');
    });

});


// Route::get('/dashboard', function () {
//     return view('dashboard');
// })->middleware(['auth'])->name('dashboard');


require __DIR__ . '/auth.php';

app/Models/Vat.php
<?php
namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * Class Association
 * @package App\Models
 *
 * @property int            id
 * @property string         title
 * @property decimal        rate
 * @property boolean        default
 * @property null|Carbon    created_at
 * @property null|Carbon    updated_at
 */
class Vat extends Model {

    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'vats';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'title',
        'rate',
    ];


    /*
      |-------------------------------------------------------------------------
      | Relationships
      |-------------------------------------------------------------------------
     */

    /**
     * Get the products
     */
    public function products()
    {
        return $this->hasMany(Product::class);
    }


    /*
      |-------------------------------------------------------------------------
      | Query scopes
      |-------------------------------------------------------------------------
     */ 

    /**
     * @param \Illuminate\Database\Query\Builder $query
     * @param String $search
     * @return \Illuminate\Database\Query\Builder
     */
    public function scopeSearch($query, $search) {

        if (blank($search) || $search == 'all_vats') {

            return $query;
        }

        return $query->where(function ($query) use ($search) {

            $query->where('title', 'like', '%' . $search . '%')
                ->orWhere('rate', 'like', '%' . $search . '%');
        });
    }


    /*
      |-------------------------------------------------------------------------
      | Accessors
      |-------------------------------------------------------------------------
     */
}

app/Http/Controllers/Admin/VatsController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Models\Vat;
use App\Http\Requests\Vats\StoreVatRequest;
use App\Http\Controllers\Controller;

class VatsController extends Controller
{
    /**
     * Show all vats
     *
     * @return \Illuminate\View\View
     */
    public function index()
    {
        return view('admin.vats.index')->with('vats', Vat::all());
    }

    /**
     * Create new vat
     *
     * @return \Illuminate\View\View
     */
    public function create()
    {
        return view('admin.vats.create');
    }

    /**
     * Edit vat
     *
     * @param Vat $vat
     * 
     * @return \Illuminate\View\View
     */
    public function edit(Vat $vat)
    {
        return view('admin.vats.edit')->with('vat', $vat);
    }

    /**
     * Store new vat
     *
     * @param StoreVatRequest $request
     */
    public function store(StoreVatRequest $request)
    {
        $vat = new Vat();
        $vat->fill($request->only($vat->getFillable()));

        if ($request->default) {

            Vat::query()->update(['default' => 0]);
            $vat->default = 1;
        }

        $vat->save();
        
        return redirect()->route('vats.index')->with('message', 'BTW tarief toegevoegd');
    }

    /**
     * Update vat
     *
     * @param StoreVatRequest $request
     * @param Vat $vat
     */
    public function update(StoreVatRequest $request, Vat $vat)
    {
        $vat->update($request->only($vat->getFillable()));

        if ($request->default) {

            Vat::query()->update(['default' => 0]);
            $vat->default = 1;
        } else {

            $vat->default = 0;
        }

        $vat->save();
        
        return redirect()->route('vats.index')->with('message', 'BTW tarief is gewijzigd');
    }

    /**
     * Delete vat
     *
     * @param Vat $vat
     */
    public function delete(Vat $vat)
    {
        $vat->delete();

        return redirect()->route('vats.index')->with('message', 'BTW tarief is verwijderd');
    }

    /**
     * Get vats index table
     *
     * @param String $search
     */
    public function getVatsIndexTable(String $search)
    {
        $vats = Vat::search($search)->get();
                    
        $html = view('admin.partials.vats.index_table', compact('vats'))->render();

        return $html;
    }
}

resources/views/admin/vats/create.blade.php
@extends('layouts.dashboard')

@section('content')

    <div class="container mt-5 pb-3">
        <div class="row">
            <div class="col-12">
                <a href="{{route('vats.index')}}"><i class="fas fa-arrow-left"></i> {{__('Terug')}}</a>
                <div class="card mt-3">
                    <div class="card-body">
                        <div class="card-title">
                            <h2>{{__('BTW tarief toevoegen')}}</h2>
                        </div>
                        <hr/>
                        <form action="{{route('vats.store')}}" method="POST" enctype="multipart/form-data">
                            @csrf
        
                            <div class="form-group">
                                <label for="title">{{__('Titel')}}</label>
                                <input type="text" name="title" class="form-control @error('title') is-invalid @enderror"/>

                                @error('title')
                                    <div class="alert alert-danger mt-3">{{ $message }}</div>
                                @enderror
                            </div>

                            <div class="form-group">
                                <label for="rate">{{__('Tarief')}}</label>
                                <input type="number" name="rate" min="0" step=".01" class="form-control @error('rate') is-invalid @enderror"/>

                                @error('rate')
                                    <div class="alert alert-danger mt-3">{{ $message }}</div>
                                @enderror
                            </div>

                            <div class="form-check">
                                <input type="checkbox" class="form-check-input" name="default" id="default">
                                <label class="form-check-label" for="default">{{__('Default')}}</label>

                                @error('default')
                                    <div class="alert alert-danger mt-3">{{ $message }}</div>
                                @enderror
                            </div>
        
                            <div class="form-group text-right">
                                <button type="submit" class="btn btn-primary">{{__('Opslaan')}}</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/vats/edit.blade.php
@extends('layouts.dashboard')

@section('content')

    <div class="container mt-5 pb-3">
        <div class="row">
            <div class="col-12">
                <a href="{{route('vats.index')}}"><i class="fas fa-arrow-left"></i> {{__('Terug')}}</a>
                <div class="card mt-3">
                    <div class="card-body">
                        <div class="card-title">
                            <h2>{{$vat->title}}</h2>
                        </div>
                        <hr/>
                        <form action="{{route('vats.update', $vat->id)}}" method="POST" enctype="multipart/form-data">
                            @csrf
        
                            <div class="form-group">
                                <label for="title">{{__('Titel')}}</label>
                                <input type="text" name="title" class="form-control @error('title') is-invalid @enderror" value="{{$vat->title}}"/>

                                @error('title')
                                    <div class="alert alert-danger mt-3">{{ $message }}</div>
                                @enderror
                            </div>

                            <div class="form-group">
                                <label for="rate">{{__('Tarief')}}</label>
                                <input type="number" name="rate" min="0" step=".01" class="form-control @error('rate') is-invalid @enderror" value="{{$vat->rate}}"/>

                                @error('rate')
                                    <div class="alert alert-danger mt-3">{{ $message }}</div>
                                @enderror
                            </div>

                            <div class="form-check">
                                <input type="checkbox" class="form-check-input" name="default" id="default" {{$vat->default ? 'checked="checked"' : ''}}>
                                <label class="form-check-label" for="default">{{__('Default')}}</label>

                                @error('default')
                                    <div class="alert alert-danger mt-3">{{ $message }}</div>
                                @enderror
                            </div>
        
                            <div class="form-group text-right">
                                <button type="submit" class="btn btn-primary">{{__('Opslaan')}}</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/vats/index.blade.php
@extends('layouts.dashboard')

@section('content')

    <div class="container mt-5 pb-3">

        @if (session('message'))
            <div class="row">
                <div class="col-12">
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        {{session('message')}}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                </div>
            </div>
        @endif

        <div class="row">
            <div class="col-4">
                <a href="{{route('dashboard')}}"><i class="fas fa-arrow-left"></i> {{__('Terug')}}</a>
            </div>
            <div class="col-8 mb-3 text-right">
                <a href="{{route('vats.create')}}" class="btn btn-primary mb-3"><i class="fas fa-plus"></i> {{__('BTW tarief toevoegen')}}</a>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-xs-12 col-sm-4">
                                <div class="form-group">
                                    <label for="vat-search">{{__('Zoeken')}}</label>
                                    <input type="text" name="vat-search" class="form-control" id="vat-search"/>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h2 class="card-title">{{__('BTW tarieven')}}</h2>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table vats-table">
                                <thead>
                                    <tr>
                                        <th>{{__('Titel')}}</th>
                                        <th>{{__('Tarief')}}</th>
                                        <th>{{__('Default')}}</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($vats as $vat)

                                        <tr>
                                            <td>
                                                <a href="{{route('vats.edit', $vat->id,)}}">{{$vat->title}}</a>
                                            </td>
                                            <td>{{$vat->rate}}%</td>
                                            <td>{{$vat->default ? __('Ja') : '-'}}</td>
                                            <td>
                                                <a href="#" type="button" data-toggle="modal" data-target="#delete-vat-modal-{{$vat->id}}" class="text-danger"><i class="fas fa-trash"></i></a>

                                                <div id="delete-vat-modal-{{$vat->id}}" tabindex="-1" role="dialog" aria-hidden="true" class="modal fade">
                                                    <div role="document" class="modal-dialog">
                                                        <div class="modal-content">
                                                            <div class="modal-header">
                                                                <h5 id="exampleModalLabel" class="modal-title">{{__('BTW tarief verwijderen')}}?</h5>
                                                                <button type="button" data-dismiss="modal" aria-label="Close" class="close">
                                                                    <span aria-hidden="true">×</span>
                                                                </button>
                                                            </div>
                                                            <div class="modal-body">
                                                                <p>
                                                                    {{__('Weet u zeker dat u')}} <b>{{$vat->title}}</b> {{__('wilt verwijderen')}}?
                                                                </p>
                                                            </div>
                                                            <div class="modal-footer">
                                                                <button type="button" data-dismiss="modal" class="btn btn-secondary">{{__('Annuleren')}}</button>
                                                                <a href="{{route('vats.delete', $vat->id)}}" class="btn btn-danger">{{__('Verwijderen')}}</a>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection